[mongodb]
server = "127.0.0.1"
port = "27017"
database = "scrapy"
[mailSetting]
server = "smtp.gmail.com"
port = "465"
email = "wayne011872@gmail.com"
password = "ckevrwbinlpkntre"
to_email = "wayne011852@gmail.com"